### PR TITLE
bugfix

### PR DESCRIPTION
**Pull request by ryanbrinn**
Bugfixes

What does this Pull Request do?

Two bugs in DefaultController:: islandora_add_datastream_form_autocomplete_callback()
How should this be tested?

A description of what steps someone could take to:
General smoke testing. Called from /islandora/object/{object}/manage/datastreams/add/autocomplete

### CODE REVIEW

**Comment by adam-vessey** [comment]
Is... this function actually cruft? As in... it's [also in the controller](https://github.com/discoverygarden/islandora/pull/5/files#diff-98946bfce0b9dc81a3190e890404b02aR496), which is probably the one referenced in the route?

**Comment by ryanbrinn** [comment]
This is the controller method. Is the name throwing you off? This bugfix is applied separately so the name change isn't applied yet.

**Comment by adam-vessey** [comment]
Ah, derp... yep.

**Comment by adam-vessey** [comment]
I think part of it was grabbing the [other PR](https://github.com/discoverygarden/islandora/pull/5) and seeing issues relating to this piece of code also:
```
FILE: ...8/modules/contrib/islandora/src/Controller/DefaultController.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
----------------------------------------------------------------------
 281 | WARNING | Unused variable $output.
 285 | WARNING | Variable $ouput is undefined.
----------------------------------------------------------------------
```
... which _this_ PR fixes... just... yeah... weird.

**Pull request merged**
